config/routes.rb
Rails.application.routes.draw do
  resources :photos
  root "photos#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
  has_one_attached :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]

  def index
    @photos = Photo.all
  end

  def show
  end

  def new
    @photo = Photo.new
  end

  def edit
  end

  def create
    @photo = Photo.new photo_params
    image = params[:photo][:image]
    caption = params[:photo][:caption]

    if @photo.save
      @photo.image.attach image if image
      redirect_to photos_path, notice: "Photo was successfully uploaded."
    else
      flash.now[:alert] = "Photo could not be saved."
      render :new
    end
  end

  def update
    respond_to do |format|
      if @photo.update photo_params
        format.html { redirect_to @photo, notice: "Photo was successfully updated." }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @photo.image.purge
    @photo.destroy
    redirect_to photos_path, notice: "Photo successfully deleted"
  end

  private

  def set_photo
    @photo = Photo.find params[:id]
  end

  def photo_params
    params.require(:photo).permit(:caption)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
  def image_url photo
    case Rails.application.config.active_storage.service
    when :local
      url_for photo.image
    when :google
      "https://storage.googleapis.com/#{ENV['STORAGE_BUCKET_NAME']}/#{photo.image.key}"
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsCatAlbum</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-dark bg-primary">
        <span class="navbar-brand mb-0 h1">Cat Photo Album</span>
      </nav>
    </header>
    
    <main> 
      <%= yield %>
    </main>
    
  </body>
</html>

app/views/photos/_form.html.erb
<%= form_with(model: photo) do |form| %>
  <% if photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
        <% photo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :caption %>
    <%= form.text_area :caption %>
  </div>

  <div class="actions">
    <%= form.submit  %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<div class="show-content">
  <h2>Editing Photo</h2>

  <%= render 'form', photo: @photo %>
  <br>
  <%= link_to 'Show', @photo, class:"btn btn-primary" %>
  <%= link_to 'Back', photos_path, class:"btn btn-primary" %>
<div class="show-content">

app/views/photos/index.html.erb
<br>
<div class="container">
    <div class="row justify-content-center">
    <%= link_to 'New Photo', new_photo_path, class:"btn btn-info show" %>
    </div>
</div>
<br>

<% if @photos.empty? %>
  <div class="container">
    <div class="row justify-content-center">
    <p>Album is empty. Click on "New Photo" to add a photo.</p>
    </div>
  </div>
<% else %>
  <div class="grid-container">
    <% @photos.each do |photo| %>
      <div class="card" style="width: 18rem;">
        <div class="card-body">
          <img class="card-img-top" src="<%= image_url photo %>" alt="Card image cap">
          <h5 class="card-title"><%= photo.caption %></h5>
          <%= link_to 'Show', photo_path(photo), class:"btn btn-primary" %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/photos/new.html.erb
<div class="container">
  <h4>Add a photo</h4>

  <%= form_for @photo, url: {action: "create"}, html: {class: "nifty_form"} do |form| %>

    <div class="row">
      <div class= "btn blue darken-2">
        <%= form.label :file %>
        <%= form.file_field :image %>
      </div>
    </div>

    <div class="row">
      <div class="input-field col s6">
        <%= form.label :caption %>
        <%= form.text_field :caption, size: 50, class: "validate" %>
      </div>
    </div>

    <button class="btn btn-success" type="commit" name="action">
      Submit
    </button>

    <%= link_to('Cancel', photos_path) %>

  <% end %>
</div>

app/views/photos/show.html.erb
<div class="show-content">

  <h2>Photo detail</h2>

  <div class="card" style="width: 30rem;">
    <div class="card-body">
      <img class="card-img-top" src="<%= image_url @photo %>" alt="Card image cap">
      <h5 class="card-title"><%= @photo.caption %></h5>
      <%= link_to 'Edit', edit_photo_path(@photo), class:"btn btn-light" %>
      <%= link_to 'Back', photos_path, class:"btn btn-light" %>
      <%= link_to 'Destroy', @photo, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>
    </div>
  </div>
</div>